Algoritmo "test-enquanto"




Var
     x, y : inteiro


Inicio
      escreval("Digite dois numero: ")
      leia(x)
      leia(y)
      
 
      enquanto x <> y faca   //enquanto x for diferente de y faça.
          se x < y entao
             escreval("CRESCENTE ")
          senao
               escreval("DECRESCENTE ")
          fimse
          
          escreval("Digite outros dois numero: ")
          leia(x)
          leia(y)

      fimenquanto

      
      


Fimalgoritmo