Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/11/2024
Var
N, i, produto : inteiro


Inicio

escreva("Deseja a tabuada para qual valor? ")
      leia(N)

      para i de 1 ate 10 faca

      produto <- N * i

      escreval(N, " x ", i, " = ", produto)

      fimpara


Fimalgoritmo